### ISSUE TITLE
Does not build in linux, "unresolved import std::os::macos

### ISSUE THREAD

**Issue by pspbar** [LeNomDesFleurs/Laminaria#1]
Trying to build in voidlinux X86_64:
git clone repo
cd repo
cargo build --release
 
(...)
   Compiling midir v0.10.0
   Compiling Laminaria v0.1.0 (/home/benalb/tmp/Laminaria)
error[E0432]: unresolved import `std::os::macos`
  --> src/ui.rs:13:14
   |
13 | use std::os::macos::raw;
   |              ^^^^^ could not find `macos` in `os`
   |
note: found an item that was configured out
  --> /builddir/rust-1.79.0/library/std/src/os/mod.rs:134:9
   = note: the item is gated behind the `macos` feature
(...)

**Comment by LeNomDesFleurs** [comment]
Hi !
Does it work if you comment the line ?
I wonder if it isn't a vestige of an older implementation that isn't in use...
I don't have access to my computer before a week : if commenting work, don't hesitate to make a pull request

**Comment by pspbar** [comment]
Yep,it compiles commenting out the line in src/ui.rs.  Will try tomorrow with orca and if it goes everything ok, I'll PR.  Thank you very much.

**Comment by LeNomDesFleurs** [comment]
Thanks for the issue, come back to me if you have any feedback / problem
