### ISSUE TITLE
Does not work with orca-c

### ISSUE THREAD

**Issue by pspbar** [LeNomDesFleurs/Laminaria#3]
I've been using Laminaria for a couple of days with Orca, the electron version, and really liked it,  launched for or five Laminarias and get lots of fun with Orca in five channels. So far so good. 

The thing is that being Laminaria a synth in the terminal, I just thought that it would be great to multiplex the terminal with tmux or screen, launch 4 Laminarias, and use [orca-c](https://github.com/hundredrabbits/Orca-c). But when I select the Midi Through Port in the orca-c menu, got this error:

thread 'midir ALSA input handler (port 'midir-read-input')' panicked at src/midi.rs:148:53:
index out of bounds: the len is 1 but the index is 1

**Comment by LeNomDesFleurs** [comment]
Hey, happy that you are playing with it, I haven't tried it myself, but indeed tmux + laminaria was on the back of my head while working on the project ;)
I've tried a fix, git pull and tell me if it solve the issue !

**Comment by pspbar** [comment]
That did the trick, thank you very much.
