### ISSUE TITLE
command line flag to change midi channel on launch.

### ISSUE THREAD

**Issue by pspbar** [LeNomDesFleurs/Laminaria#4]
It would be great to launch Laminaria with a flag, like -C or -c to start in a defined channel, useful when launching seversal instances in a multiplexed terminal, so you do not have to change the channel using the > and < keys.

**Comment by LeNomDesFleurs** [comment]
I added it, -c or --channel <number> now let you set channel at startup (channel will be set to zero if you change port at runtime), value superior to 15 will be clipped to 15, close the issue if it works properly on you side

**Comment by pspbar** [comment]
Thank you very much.
